#!/usr/bin/env python3
"""Regenerate the ARC-AGI-3 submission notebook from committed sources.

The Kaggle kernel notebook ``notebooks/arc3_submission_kernel/submission.ipynb`` is the
only deployment artifact for the ARC-AGI-3 agent (the runner cell gates the real run
behind ``KAGGLE_IS_COMPETITION_RERUN``). It used to be assembled by hand, so it drifted
from ``src/`` and shipped a pre-fix, non-reproducible seed. This script removes the
hand-maintenance: the agent cell is copied byte-for-byte from
``src/arc3_spatial_memory_agent.py`` and the other four cells are carried here as
templates, so the whole notebook can be regenerated and verified.

Usage::

    python3 scripts/build_arc3_notebook.py            # write the notebook
    python3 scripts/build_arc3_notebook.py --check    # exit 0 iff on-disk == generated

The script is pure standard library so it runs under the system ``python3`` with no
third-party imports.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENT_SOURCE_DEFAULT = REPO_ROOT / "src" / "arc3_spatial_memory_agent.py"
NOTEBOOK_DEFAULT = REPO_ROOT / "notebooks" / "arc3_submission_kernel" / "submission.ipynb"

#: First line of the agent cell; the body that follows it must equal the source file.
WRITEFILE_LINE = "%%writefile /tmp/my_agent.py"

#: Seed pinned on the agent launch command. See HEADER_CELL_SOURCE for the rule that
#: selects it: the seed whose measured score is the median of the pre-registered list.
DEPLOYED_SEED = "16"

#: The four cells that are not derived from ``src/``. Cell 0 states the notebook's real
#: provenance and the deployment seed rule; cells 1, 3 and 4 preserve the runner
#: semantics of the original notebook (pip install, competition-rerun runner, commit-mode
#: dummy submission). The only intended change to cell 3 is the ``ARC3_AGENT_SEED`` line.
HEADER_CELL_SOURCE = '''# ARC Prize 2026 — ARC-AGI-3 Submission

Generated by `scripts/build_arc3_notebook.py` from `src/arc3_spatial_memory_agent.py`.
Do not edit cells directly — edit the source file and re-run
`python3 scripts/build_arc3_notebook.py`, then confirm with
`python3 scripts/build_arc3_notebook.py --check`.

## Deployment seed

The runner pins `ARC3_AGENT_SEED=16` on the agent launch command. The agent is a
high-variance policy and the leaderboard samples one trajectory, so the deployed seed is
chosen by a rank rule, not for its value: seed 16 is the seed whose measured score
(0.4042) is the **median** of the pre-registered fixed list `1..20` (median 0.4052),
measured over the full 25 released games. A median is a rank statistic, not an optimum.
The maximum (seed 15 = 0.9859) is explicitly rejected: selecting it fits the 25 games
that constitute the test set. The full distribution is recorded in
`odd/tasks/arc3-notebook-builder.md` §2, so any reader can re-run any seed and check both
numbers. Without the override the agent falls back to its default seed
(`zlib.crc32(game_id)`), which measures 0.2017 — a regression against the deployed v2
baseline of 0.28.'''

CELL_1_SOURCE = r'''!pip install --no-index --find-links \
    /kaggle/input/competitions/arc-prize-2026-arc-agi-3/arc_agi_3_wheels \
    arc-agi python-dotenv'''

CELL_3_SOURCE = r'''import os

if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
    # Wait for the gateway sidecar to be ready.
    !curl --fail --retry 999 --retry-all-errors --retry-delay 5 \
          --retry-max-time 600 http://gateway:8001/api/games

    # Copy the framework into a writable location.
    !cp -r /kaggle/input/competitions/arc-prize-2026-arc-agi-3/ARC-AGI-3-Agents \
           /kaggle/working/ARC-AGI-3-Agents

    # Drop our agent in as a framework template.
    !cp /tmp/my_agent.py \
        /kaggle/working/ARC-AGI-3-Agents/agents/templates/my_agent.py

    # Register MyAgent in the framework's agent registry. We rewrite
    # __init__.py because the upstream version eagerly imports
    # templates with deps we don't ship (langgraph, smolagents, etc.).
    with open('/kaggle/working/ARC-AGI-3-Agents/agents/__init__.py', 'w') as f:
        f.write("""from typing import Type
from dotenv import load_dotenv
from .agent import Agent, Playback
from .swarm import Swarm
from .templates.random_agent import Random
from .templates.my_agent import MyAgent

load_dotenv()

AVAILABLE_AGENTS: dict[str, Type[Agent]] = {
    'random': Random,
    'myagent': MyAgent,
}
""")

    # Point the framework at the gateway sidecar.
    with open('/kaggle/working/ARC-AGI-3-Agents/.env', 'w') as f:
        f.write("""SCHEME=http
HOST=gateway
PORT=8001
ARC_API_KEY=test-key-123
ARC_BASE_URL=http://gateway:8001/
OPERATION_MODE=online
ENVIRONMENTS_DIR=
RECORDINGS_DIR=/kaggle/working/server_recording
""")

    # Run it. The gateway records every action and emits submission.parquet.
    !cd /kaggle/working/ARC-AGI-3-Agents && \
        MPLBACKEND=agg \
        ARC3_AGENT_SEED=16 \
        python main.py --agent myagent
'''

CELL_4_SOURCE = r'''import os
if not os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
    # Save-and-run-all (commit) mode: emit a dummy submission so the
    # commit succeeds. The real submission.parquet is produced by the
    # gateway during competition rerun.
    import pandas as pd
    submission = pd.DataFrame(
        data=[['1_0', '1', True, 1]],
        columns=['row_id', 'game_id', 'end_of_game', 'score'])
    submission.to_parquet('/kaggle/working/submission.parquet', index=False)
    submission.head()
'''

# Key order is significant: it is what ``json.dumps`` preserves and what keeps the
# regenerated file byte-identical to the committed notebook.
NOTEBOOK_METADATA = {
    "kernelspec": {
        "language": "python",
        "display_name": "Python 3",
        "name": "python3",
    },
    "language_info": {
        "name": "python",
        "mimetype": "text/x-python",
        "file_extension": ".py",
        "pygments_lexer": "ipython3",
    },
    "kaggle": {
        "accelerator": "nvidiaTeslaT4",
        "isInternetEnabled": False,
        "isGpuEnabled": True,
        "language": "python",
        "sourceType": "notebook",
    },
}


def agent_cell_source(agent_source: str) -> str:
    """Return the ``%%writefile`` cell whose body is the agent source, unchanged."""
    return f"{WRITEFILE_LINE}\n{agent_source}"


def build_notebook(agent_source: str) -> dict:
    """Build the notebook document as a plain dict in the committed key order."""
    code_cell = lambda source: {  # noqa: E731 - tiny local helper, mirrors nbformat defaults
        "cell_type": "code",
        "metadata": {"trusted": True},
        "outputs": [],
        "execution_count": None,
        "source": source,
    }
    return {
        "metadata": NOTEBOOK_METADATA,
        "nbformat_minor": 4,
        "nbformat": 4,
        "cells": [
            {"cell_type": "markdown", "metadata": {}, "source": HEADER_CELL_SOURCE},
            code_cell(CELL_1_SOURCE),
            code_cell(agent_cell_source(agent_source)),
            code_cell(CELL_3_SOURCE),
            code_cell(CELL_4_SOURCE),
        ],
    }


def render_notebook(notebook: dict) -> str:
    """Serialise the notebook exactly as the committed artifact stores it."""
    return json.dumps(notebook, indent=1)


def generate(agent_source_path: Path) -> str:
    """Read the agent source and return the full notebook text."""
    agent_source = Path(agent_source_path).read_text(encoding="utf-8")
    return render_notebook(build_notebook(agent_source))


def _cell_source(cell: dict) -> str:
    source = cell.get("source", "")
    if isinstance(source, list):  # tolerate nbformat's line-list form
        source = "".join(source)
    return source


def _clip(text: str, limit: int = 240) -> str:
    if len(text) <= limit:
        return text
    return f"{text[:limit]}… (+{len(text) - limit} chars)"


def describe_differences(actual: dict, expected: dict) -> list[str]:
    """Return a short, readable summary of how the on-disk notebook drifted."""
    lines: list[str] = []
    if actual.get("metadata") != expected.get("metadata"):
        lines.append("metadata differs")
    for key in ("nbformat", "nbformat_minor"):
        if actual.get(key) != expected.get(key):
            lines.append(
                f"{key}: on-disk={actual.get(key)!r} generated={expected.get(key)!r}"
            )

    actual_cells = actual.get("cells", [])
    expected_cells = expected.get("cells", [])
    if len(actual_cells) != len(expected_cells):
        lines.append(
            f"cell count: on-disk={len(actual_cells)} generated={len(expected_cells)}"
        )

    for index, (a_cell, e_cell) in enumerate(zip(actual_cells, expected_cells)):
        if a_cell == e_cell:
            continue
        if a_cell.get("cell_type") != e_cell.get("cell_type"):
            lines.append(
                f"cell {index}: cell_type on-disk={a_cell.get('cell_type')!r} "
                f"generated={e_cell.get('cell_type')!r}"
            )
            continue
        a_src = _cell_source(a_cell)
        e_src = _cell_source(e_cell)
        if a_src != e_src:
            lines.append(
                f"cell {index} source differs: on-disk {len(a_src.splitlines())} lines "
                f"vs generated {len(e_src.splitlines())} lines"
            )
            diff = list(
                difflib.unified_diff(
                    a_src.splitlines(),
                    e_src.splitlines(),
                    fromfile=f"on-disk cell {index}",
                    tofile=f"generated cell {index}",
                    lineterm="",
                )
            )
            for diff_line in diff[:24]:
                lines.append("  " + _clip(diff_line))
            if len(diff) > 24:
                lines.append(f"  … ({len(diff) - 24} more diff lines)")
        else:
            lines.append(f"cell {index}: non-source fields differ (metadata/outputs)")
    if not lines:
        lines.append("notebook JSON differs at an unrecognised level")
    return lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the ARC-AGI-3 submission notebook from committed sources."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the on-disk notebook with the generated one; exit non-zero on drift",
    )
    parser.add_argument(
        "--notebook",
        type=Path,
        default=NOTEBOOK_DEFAULT,
        help="notebook path (default: %(default)s)",
    )
    parser.add_argument(
        "--agent-source",
        type=Path,
        default=AGENT_SOURCE_DEFAULT,
        help="agent source path (default: %(default)s)",
    )
    args = parser.parse_args(argv)

    try:
        generated = generate(args.agent_source)
    except OSError as exc:
        print(f"error: cannot read agent source {args.agent_source}: {exc}", file=sys.stderr)
        return 2

    if args.check:
        if not args.notebook.exists():
            print(f"error: notebook not found: {args.notebook}", file=sys.stderr)
            return 2
        actual_text = args.notebook.read_text(encoding="utf-8")
        if actual_text == generated:
            print(f"OK: {args.notebook} matches the generated notebook")
            return 0
        print(
            f"DRIFT: {args.notebook} differs from the generated notebook",
            file=sys.stderr,
        )
        try:
            actual_nb = json.loads(actual_text)
            expected_nb = json.loads(generated)
        except json.JSONDecodeError as exc:
            print(f"  on-disk notebook is not valid JSON: {exc}", file=sys.stderr)
            return 1
        for line in describe_differences(actual_nb, expected_nb):
            print("  " + line, file=sys.stderr)
        return 1

    args.notebook.parent.mkdir(parents=True, exist_ok=True)
    args.notebook.write_text(generated, encoding="utf-8")
    print(f"wrote {args.notebook} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
