#!/usr/bin/env python3
"""Regenerate the ARC-AGI-2 submission notebook from committed sources.

The Kaggle kernel notebook
``notebooks/arc2_submission_kernel/kaggle_arc2_submission.ipynb`` inlines the
dual-process solver by hand, so it drifted 111 lines behind
``src/arc2_dual_process_solver.py`` and kept two dead paths in the artifact that was
actually submitted as the ARC-AGI-2 entry:

* a dead primitive — the deployed ``rot270`` subscripted a ``zip`` iterator and raised
  ``TypeError: 'zip' object is not subscriptable`` on every call, so every ``rot270``
  candidate was silently dropped;
* a dead dispatch — ``matching_solvers`` holds ``(name, fn)`` tuples, but the deployed
  code called ``matching_solvers[0](inp)``, raising ``TypeError: 'tuple' object is not
  callable`` on the coverage branch.

This script removes the hand-maintenance. Cell 2 is copied **byte-for-byte** from
``src/arc2_dual_process_solver.py`` and the other three cells are carried here as
templates, so the whole notebook can be regenerated and verified.

Usage::

    python3 scripts/build_arc2_notebook.py            # write the notebook
    python3 scripts/build_arc2_notebook.py --check    # exit 0 iff on-disk == generated

The script is pure standard library so it runs under the system ``python3`` with no
third-party imports.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOLVER_SOURCE_DEFAULT = REPO_ROOT / "src" / "arc2_dual_process_solver.py"
NOTEBOOK_DEFAULT = (
    REPO_ROOT / "notebooks" / "arc2_submission_kernel" / "kaggle_arc2_submission.ipynb"
)

#: Cell 0. It states the notebook's real provenance and — critically — does not claim the
#: live kernel is what was scored. The revision deployed as the ARC-AGI-2 submission on
#: 2026-09-23 was the pre-repair revision carrying both dead paths of
#: ``odd/tasks/arc2-submission-builder.md`` §2.
HEADER_CELL_SOURCE = '''# Dual-Process Heuristic Gating & Program Synthesis — ARC-AGI-2 Submission

Generated by `scripts/build_arc2_notebook.py` from `src/arc2_dual_process_solver.py`.
Do not edit cells directly — edit the source file and re-run
`python3 scripts/build_arc2_notebook.py`, then confirm with
`python3 scripts/build_arc2_notebook.py --check`.

Paper: *Dual-Process Heuristic Gating for ARC-AGI*. Author: Sergio Alberto Dominguez
(@ser8147). Kernel: `ser8147/arc-laya-dual-process-submission` — a model-free symbolic
solver that consumes no dataset.

## Provenance and deployment status

**This notebook is not the revision that was scored.** The version deployed as the
ARC-AGI-2 submission on 2026-09-23 was the pre-repair revision, and it carried two dead
paths:

1. A dead primitive: `("rot270", lambda g: [list(x) for x in zip(*g)[::-1]])` raised
   `TypeError: 'zip' object is not subscriptable` on every call, so every `rot270`
   candidate was silently dropped.
2. A dead dispatch: `matching_solvers` holds `(name, fn)` tuples, but the deployed code
   called `matching_solvers[0](inp)`, raising `TypeError: 'tuple' object is not callable`
   on the coverage branch.

The submission cell carries no exception handling, so a raise would have aborted the loop
and written no `submission.json`. A complete 240-key `submission.json` exists, so no test
input ever reached the `matching_solvers` branch: the deployed solver's coverage on the
hidden test set was exactly zero, and every submitted output was fallback
(`fallback_1` / `fallback_2`). See `odd/tasks/arc2-submission-builder.md` §2 for the
measurement and the artifact buckets.

## What this revision changes

- Cell 2 is regenerated from `src/`, so both dead paths above are repaired.
- Cell 3 reports **coverage** (tasks whose candidate reproduced every training pair, and
  the echo/zero/other output buckets) instead of printing a submission-key count as
  evidence of work.

Re-deploying this notebook is a separate, owner-owned decision (`ASB6`). This artifact
describes the deployed revision; it does not silently redefine it.'''

#: Cell 1. Loads the competition test inputs. Unchanged from the deployed kernel: the
#: ``Path`` import is used by cell 3's coverage report.
CELL_1_SOURCE = r'''import os, json, glob
from pathlib import Path

# Locate competition test input
test_files = glob.glob("/kaggle/input/**/arc-agi_test_challenges.json", recursive=True)
sample_files = glob.glob("/kaggle/input/**/sample_submission.json", recursive=True)

assert test_files, "arc-agi_test_challenges.json not found in /kaggle/input!"
test_path = test_files[0]
sample_path = sample_files[0] if sample_files else None

print(f"Loaded test challenges from: {test_path}")
with open(test_path, "r", encoding="utf-8") as f:
    test_tasks = json.load(f)

print(f"Total tasks to solve: {len(test_tasks)}")
'''

#: Cell 3. Reports coverage, not a key count. This is a deliberate behaviour change:
#: the deployed cell printed ``✅ Generated ... with {len(submission)} tasks!``, which is a
#: count of dictionary keys — the artifact scored 0.00 while reporting "240 tasks".
CELL_3_SOURCE = r'''submission = {}
tasks_with_coverage = 0
tasks_fell_back = 0
buckets = {"echo_input": 0, "zero_grid": 0, "other": 0}
failure_examples = {}


def classify_output(inp, out):
    if out is None:
        return "other"
    if out == inp:
        return "echo_input"
    if all(cell == 0 for row in out for cell in row):
        return "zero_grid"
    return "other"


for task_id, task in test_tasks.items():
    trace = {}
    submission[task_id] = solve_arc_task(task, trace)

    if trace.get("n_matching", 0) > 0:
        tasks_with_coverage += 1
    else:
        tasks_fell_back += 1
        if trace.get("failures"):
            name, err = next(iter(trace["failures"].items()))
            failure_examples.setdefault(name, err)

    for test_item, attempt in zip(task["test"], submission[task_id]):
        buckets[classify_output(test_item["input"], attempt["attempt_1"])] += 1

n_test_outputs = sum(buckets.values())

output_path = "/kaggle/working/submission.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(submission, f)

file_size_kb = Path(output_path).stat().st_size / 1024
print(f"Wrote {output_path} ({file_size_kb:.1f} KB): {len(submission)} submission keys, {n_test_outputs} test outputs")
print(f"Coverage: {tasks_with_coverage}/{len(submission)} tasks had a candidate that reproduced every training pair")
print(f"Fallback: {tasks_fell_back}/{len(submission)} tasks had no matching candidate and used fallback_1/fallback_2")
print(f"attempt_1 buckets: echo_input={buckets['echo_input']} zero_grid={buckets['zero_grid']} other={buckets['other']}")
if failure_examples:
    print(f"Candidate failures (first per name, {len(failure_examples)} names): {failure_examples}")
if tasks_with_coverage == 0:
    print("WARNING: coverage is zero — every submitted output is a fallback, not a solve.")
else:
    print(f"RESULT: {tasks_with_coverage} task(s) had true solver coverage.")
'''

# Key order is significant: it is what ``json.dumps`` preserves and what keeps the
# regenerated file byte-identical to the committed notebook.
NOTEBOOK_METADATA = {
    "kernelspec": {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    },
    "language_info": {
        "name": "python",
        "version": "3",
    },
}


def build_notebook(solver_source: str) -> dict:
    """Build the notebook document as a plain dict in the committed key order."""
    def code_cell(source: str) -> dict:
        return {
            "cell_type": "code",
            "metadata": {"trusted": True},
            "execution_count": None,
            "outputs": [],
            "source": source,
        }

    return {
        "cells": [
            {"cell_type": "markdown", "metadata": {}, "source": HEADER_CELL_SOURCE},
            code_cell(CELL_1_SOURCE),
            # Cell 2 is the solver source, unchanged and inlined (no %%writefile).
            code_cell(solver_source),
            code_cell(CELL_3_SOURCE),
        ],
        "metadata": NOTEBOOK_METADATA,
        "nbformat": 4,
        "nbformat_minor": 4,
    }


def render_notebook(notebook: dict) -> str:
    """Serialise the notebook exactly as the committed artifact stores it."""
    return json.dumps(notebook, indent=1)


def generate(solver_source_path: Path) -> str:
    """Read the solver source and return the full notebook text."""
    solver_source = Path(solver_source_path).read_text(encoding="utf-8")
    return render_notebook(build_notebook(solver_source))


def _cell_source(cell: dict) -> str:
    source = cell.get("source", "")
    if isinstance(source, list):  # tolerate nbformat's line-list form
        source = "".join(source)
    return source


def _clip(text: str, limit: int = 240) -> str:
    if len(text) <= limit:
        return text
    return f"{text[:limit]}… (+{len(text) - limit} chars)"


def describe_differences(actual: dict, expected: dict) -> list[str]:
    """Return a short, readable summary of how the on-disk notebook drifted."""
    lines: list[str] = []
    if actual.get("metadata") != expected.get("metadata"):
        lines.append("metadata differs")
    for key in ("nbformat", "nbformat_minor"):
        if actual.get(key) != expected.get(key):
            lines.append(
                f"{key}: on-disk={actual.get(key)!r} generated={expected.get(key)!r}"
            )

    actual_cells = actual.get("cells", [])
    expected_cells = expected.get("cells", [])
    if len(actual_cells) != len(expected_cells):
        lines.append(
            f"cell count: on-disk={len(actual_cells)} generated={len(expected_cells)}"
        )

    for index, (a_cell, e_cell) in enumerate(zip(actual_cells, expected_cells)):
        if a_cell == e_cell:
            continue
        if a_cell.get("cell_type") != e_cell.get("cell_type"):
            lines.append(
                f"cell {index}: cell_type on-disk={a_cell.get('cell_type')!r} "
                f"generated={e_cell.get('cell_type')!r}"
            )
            continue
        a_src = _cell_source(a_cell)
        e_src = _cell_source(e_cell)
        if a_src != e_src:
            lines.append(
                f"cell {index} source differs: on-disk {len(a_src.splitlines())} lines "
                f"vs generated {len(e_src.splitlines())} lines"
            )
            diff = list(
                difflib.unified_diff(
                    a_src.splitlines(),
                    e_src.splitlines(),
                    fromfile=f"on-disk cell {index}",
                    tofile=f"generated cell {index}",
                    lineterm="",
                )
            )
            for diff_line in diff[:24]:
                lines.append("  " + _clip(diff_line))
            if len(diff) > 24:
                lines.append(f"  … ({len(diff) - 24} more diff lines)")
        else:
            lines.append(f"cell {index}: non-source fields differ (metadata/outputs)")
    if not lines:
        lines.append("notebook JSON differs at an unrecognised level")
    return lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the ARC-AGI-2 submission notebook from committed sources."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the on-disk notebook with the generated one; exit non-zero on drift",
    )
    parser.add_argument(
        "--notebook",
        type=Path,
        default=NOTEBOOK_DEFAULT,
        help="notebook path (default: %(default)s)",
    )
    parser.add_argument(
        "--solver-source",
        type=Path,
        default=SOLVER_SOURCE_DEFAULT,
        help="solver source path (default: %(default)s)",
    )
    args = parser.parse_args(argv)

    try:
        generated = generate(args.solver_source)
    except OSError as exc:
        print(
            f"error: cannot read solver source {args.solver_source}: {exc}",
            file=sys.stderr,
        )
        return 2

    if args.check:
        if not args.notebook.exists():
            print(f"error: notebook not found: {args.notebook}", file=sys.stderr)
            return 2
        actual_text = args.notebook.read_text(encoding="utf-8")
        if actual_text == generated:
            print(f"OK: {args.notebook} matches the generated notebook")
            return 0
        print(
            f"DRIFT: {args.notebook} differs from the generated notebook",
            file=sys.stderr,
        )
        try:
            actual_nb = json.loads(actual_text)
            expected_nb = json.loads(generated)
        except json.JSONDecodeError as exc:
            print(f"  on-disk notebook is not valid JSON: {exc}", file=sys.stderr)
            return 1
        for line in describe_differences(actual_nb, expected_nb):
            print("  " + line, file=sys.stderr)
        return 1

    args.notebook.parent.mkdir(parents=True, exist_ok=True)
    args.notebook.write_text(generated, encoding="utf-8")
    print(f"wrote {args.notebook} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
